services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        #image: sail-8.3/app
        container_name: speekmarter
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
            MARIADB_ROOT_HOST: "%"
            MARIADB_DATABASE: "${DB_DATABASE}"
            MARIADB_USER: "${DB_USERNAME}"
            MARIADB_PASSWORD: "${DB_PASSWORD}"
            MARIADB_ALLOW_EMPTY_PASSWORD: 1
            VIRTUAL_HOST: "${VIRTUAL_HOST}"
            LETSENCRYPT_HOST: "${LETSENCRYPT_HOST}"
            LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
        volumes:
            - '.:/var/www/html'
        networks:
            nginx_proxy_net:
                aliases:
                    - nginx_proxy_host
            speekmarter:
                aliases:
                    - speekmarter_host
networks:
    nginx_proxy_net:
        name: net
        driver: bridge
        external: true

    speekmarter:
        name: network_mariadb
        driver: bridge
        external: true
